export type Color =
  | 'primary'
  | 'primary-hover'
  | 'primary-resting'
  | 'primary-disabled'
  | 'primary-dark'
  | 'primary-grey'
  | 'primary-hard'
  | 'success'
  | 'success-hard'
  | 'warning'
  | 'danger'
  | 'info'
  | 'secondary'
  | 'sucess-light'
  | 'warning-light'
  | 'danger-light'
  | 'default'
  | 'white'
  | 'outline'
  | 'resting-outline'
  | 'background-light'
  | 'background-extra-light'
  | 'background-1'
  | 'background-2'
  | 'background-3'
  | 'border'

const sheepNames = ['Capn Frisky', 'Mr. Snugs', 'Lambchop'] as const
type SheepName = (typeof sheepNames)[number]
